### PR TITLE
making stuff more leet

### PR DESCRIPTION
**Pull request by cod3machin3**
because reasons... of course....

### CODE REVIEW

**Comment by jeremyprice** [comment]
uh oh, this one has conflicts.  Gonna have to go command line to fix it

**Comment by cod3machin3** [comment]
trying to follow the command line directions from github leaves me with:
git checkout -b 1337h4x0r origin/1337h4x0r
fatal: A branch named '1337h4x0r' already exists.

**Comment by jeremyprice** [comment]
@cod3machin3 since you already have the branch on your local (via the command line) you can just `checkout` that `1337h4x0r` branch on your local and do a `git merge master` from within that branch.  Then follow the "Step 2" instructions for the command line.

**Comment by jeremyprice** [comment]
It looks like @agangidi53 fixed this in his PR #22

**Comment by philip-ulrich** [comment]
Closing this PR since this was taken care of in #22.

**Pull request closed without merging**
