### PR TITLE
more kittens

### PR DESCRIPTION
**Pull request by kdorff**

### CODE REVIEW

**Comment by jeremyprice** [comment]
The world needs moar kittens!

**Comment by jeremyprice** [comment]
```
____________ 
< Moar cats! >
 ------------ 
     \
      \
       ("`-'  '-/") .___..--' ' "`-._
         ` *_ *  )    `-.   (      ) .`-.__. `)
         (_Y_.) ' ._   )   `._` ;  `` -. .-'
      _.. `--'_..-_/   /--' _ .' ,4
   ( i l ),-''  ( l i),'  ( ( ! .-'  
```

**Comment by patty086** [comment]
test comment for more kittens

**Comment by jeremyprice** [comment]
@patty086 your comment tested perfectly!

**Pull request merged**
